# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SSH deploy

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_SSH_HOST }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ./deploy && rm -rf btp-be
          mkdir btp-be
          cd ./btp-be
          git pull
          cat ../.env-indexer >> ./btp-dashboard/packages/block-indexer/.env
          cd ./btp-dashboard/packages/block-indexer
          echo "checkout be-dev branch"
          git checkout be-dev
          yarn
          echo "start block-indexer"
          pm2 start yarn --interpreter bash --name block-indexer -- start
          echo "block-indexer is starting"
          cd ../dashboard-api
          yarn
          echo "start dashboard-api"
          cat ../.env-dashboard >> ./btp-dashboard/packages/dashboard-api/.env
          pm2 start yarn --interpreter bash --name dashboard-api -- start
          echo "dashboard-api is starting"
